server:
  port: 8082
spring:
  deserializer:
    value:
      delegate:
        class: JsonDeserializer.class
    key:
      delegate:
        class: JsonDeserializer.class
  application:
    name: consumer-service
  kafka:
    consumer:
      group-id: order-group
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.software.consumerservice.utils.CustomDeserializer
      properties:
        kafka.deserializer.event.mapping: orderEvent:com.software.consumerservice.dto.OrderEvent
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
rate-limiter:
  number-of-message: 30
  duration-to-consume: 60
  thread-sleep-duration: 1000
  report-interval: 6000
management:
  tracing:
    sampling:
      probability: 1.0
